# Copyright (c) 2017, WSO2 Inc. (http://www.wso2.org) All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---
classes:
  - wso2is_analytics

wso2::service_name: wso2is_analytics
wso2::hostname: is.analytics.dev.wso2.org
wso2::mgt_hostname: is.analytics.dev.wso2.org
wso2::carbon_home_symlink: "/mnt/wso2is-analytics-%{::product_version}"
wso2::pack_filename: "wso2is-analytics-%{::product_version}.zip"

wso2::template_list:
  - repository/conf/datasources/master-datasources.xml
  - repository/conf/datasources/analytics-datasources.xml
  - repository/conf/datasources/metrics-datasources.xml
  - repository/conf/user-mgt.xml
  - repository/conf/registry.xml
  - repository/conf/metrics.xml
  - repository/conf/axis2/axis2.xml
  - repository/conf/carbon.xml
  - repository/conf/tomcat/catalina-server.xml
  - repository/conf/analytics/analytics-config.xml
  - repository/conf/analytics/my-node-id.dat
  - repository/conf/analytics/spark/spark-defaults.conf
  - repository/conf/event-processor.xml
  - repository/deployment/server/jaggeryapps/portal/configs/designer.json
  - bin/load-spark-env-vars.sh
  - bin/wso2server.sh

#  - repository/conf/security/cipher-text.properties
#  - repository/conf/security/cipher-tool.properties
#  - bin/ciphertool.sh
#  - password-tmp

# File list to be copied to the product folder, if there are changes found in the files, the system
# service will be restarted
wso2::file_list:
  - "repository/components/lib/%{hiera('wso2::datasources::mysql::connector_jar')}"

# Clustering configuration related properties of the product in repository/conf/axis2/axis2.xml
# Clustering scheme can be wka, aws, kubenetes, mesos
wso2::clustering:
  enabled: false
  domain: is.analytics.wso2.domain
  local_member_host: "%{::ipaddress}"
  local_member_port: 4000
  sub_domain: mgt
# WKA membership scheme
  membership_scheme: wka
  wka:
    members:
      -
        hostname: "%{::ipaddress}"
        port: 4000
# AWS membership scheme
#   membership_scheme: aws
#   aws:
#     access_key: access-key
#     secret_key: secret-key
#     security_group: security-group
#     host_header: host-header
#     region: region
#     tag_key: tag-key
#     tag_value: tag-value

# Datasource configuration related properties in repository/conf/datasources/master-datasources.xml
wso2::master_datasources:
  analytics_ds:
    name: WSO2_ANALYTICS_DS
    description: The datasource used for registry and user management
    driver_class_name: "%{hiera('wso2::datasources::mysql::driver_class_name')}"
    url: jdbc:mysql://192.168.100.1:3306/WSO2_ANALYTICS_DB?autoReconnect=true&amp;useSSL=false
    username: "%{hiera('wso2::datasources::mysql::username')}"
    password: "%{hiera('wso2::datasources::mysql::password')}"
    jndi_config: jdbc/WSO2AnalyticsDS
    max_active: "%{hiera('wso2::datasources::common::max_active')}"
    max_wait: "%{hiera('wso2::datasources::common::max_wait')}"
    test_on_borrow: "%{hiera('wso2::datasources::common::test_on_borrow')}"
    default_auto_commit: "%{hiera('wso2::datasources::common::default_auto_commit')}"
    validation_query: "%{hiera('wso2::datasources::mysql::validation_query')}"
    validation_interval: "%{hiera('wso2::datasources::common::validation_interval')}"

# Datasource configuration related properties in repository/conf/datasources/analytics-datasources.xml
wso2::analytics_datasources:
  analytics_store_ds:
    name: WSO2_ANALYTICS_STORE_DS
    description: The datasource used for analytics record store
    driver_class_name: "%{hiera('wso2::datasources::mysql::driver_class_name')}"
    url: jdbc:mysql://192.168.100.1:3306/WSO2_ANALYTICS_DB?autoReconnect=true&amp;useSSL=false
    username: "%{hiera('wso2::datasources::mysql::username')}"
    password: "%{hiera('wso2::datasources::mysql::password')}"
    max_active: "%{hiera('wso2::datasources::common::max_active')}"
    max_wait: "%{hiera('wso2::datasources::common::max_wait')}"
    test_on_borrow: "%{hiera('wso2::datasources::common::test_on_borrow')}"
    default_auto_commit: "%{hiera('wso2::datasources::common::default_auto_commit')}"
    validation_query: "%{hiera('wso2::datasources::mysql::validation_query')}"
    validation_interval: "%{hiera('wso2::datasources::common::validation_interval')}"
    default_auto_commit: false
    initial_size: 0
    test_while_idle: true
    min_evictable_idle_time_millis: 4000

# Metrics datasource configuration related properties in repository/conf/datasources/metrics-datasources.xml
wso2::metrics_datasources:
  # Metrics are to be stored local to the server. Thus an embedded H2 database is used here.
  # If necessary can be pointed to an external datasource.
  metrics_ds:
    name: WSO2_METRICS_DS
    description: The default datasource used for carbon metrics
    driver_class_name: "%{hiera('wso2::datasources::h2::driver_class_name')}"
    url: jdbc:h2:repository/database/WSO2METRICS_DB;DB_CLOSE_ON_EXIT=FALSE;AUTO_SERVER=TRUE
    username: "%{hiera('wso2::datasources::common::username')}"
    password: "%{hiera('wso2::datasources::common::password')}"
    jndi_config: jdbc/WSO2_METRICS_DS
    max_active: "%{hiera('wso2::datasources::common::max_active')}"
    max_wait: "%{hiera('wso2::datasources::common::max_wait')}"
    test_on_borrow: "%{hiera('wso2::datasources::common::test_on_borrow')}"
    default_auto_commit: "%{hiera('wso2::datasources::common::default_auto_commit')}"
    validation_query: "%{hiera('wso2::datasources::mysql::validation_query')}"
    validation_interval: "%{hiera('wso2::datasources::common::validation_interval')}"

# User management admin user/role configuration and the datasource configuration in repository/conf/user-mgt.xml
wso2::user_management:
  admin_role: admin
  admin_username: "%{hiera('wso2::super_admin::username')}"
  admin_password: "%{hiera('wso2::super_admin::password')}"
  datasource: analytics_ds

# Analytics event store datasource configuration in repository/conf/analytics/analytics-config.xml
wso2::analytics_event_store_datasource: analytics_store_ds

# Analytics processed data store datasource configuration in repository/conf/analytics/analytics-config.xml
wso2::analytics_processed_data_store_datasource: analytics_store_ds

# Metrics datasource configuration in repository/conf/metrics.xml
wso2::metrics_datasource: metrics_ds

# Remote registry instance configuration related properties in repository/conf/registry.xml
wso2::registry_instances:
  shared_registry:
    datasource: analytics_ds
    read_only: false
    registry_root: /
    enable_cache: true
    overwrite: true

# Registry mount configuration in repository/conf/registry.xml
wso2::registry_mounts:
  config_registry:
    instance_id: shared_registry
    path: /_system/config
    target_path: /_system/config
    overwrite: true

  governance_registry:
    instance_id: shared_registry
    path: /_system/governance
    target_path: /_system/governance
    overwrite: true

wso2::spark:
  master: local
  master_count: 1
  hostname: "%{::ipaddress}"

wso2::ha_deployment:
  enabled: false
  eventSync:
    hostName: "%{::ipaddress}"
    port: 11224
  management:
    hostName: "%{::ipaddress}"
    port: 10005
  presentation:
    hostName: "%{::ipaddress}"
    port: 11002

## Secure vault configuration
# wso2::enable_secure_vault: true
# wso2::secure_vault_configs:
#  key_store_password:
#    secret_alias: Carbon.Security.KeyStore.Password
#    secret_alias_value: repository/conf/carbon.xml//Server/Security/KeyStore/Password,false
#    password: "%{hiera('wso2::key_stores::key_store::password')}"
#
#  key_store_key_password:
#    secret_alias: Carbon.Security.KeyStore.KeyPassword
#    secret_alias_value: repository/conf/carbon.xml//Server/Security/KeyStore/KeyPassword,false
#    password: "%{hiera('wso2::key_stores::key_store::key_password')}"
#
#  trust_store_password:
#    secret_alias: Carbon.Security.TrustStore.Password
#    secret_alias_value: repository/conf/carbon.xml//Server/Security/TrustStore/Password,false
#    password: "%{hiera('wso2::key_stores::trust_store::password')}"
#
#  connector_key_store_password:
#    secret_alias: Server.Service.Connector.keystorePass
#    secret_alias_value: repository/conf/tomcat/catalina-server.xml//Server/Service/Connector[@keystorePass],true
#    password: "%{hiera('wso2::key_stores::connector_key_store::password')}"
#
#  user_manager_admin_password:
#    secret_alias: UserManager.AdminUser.Password
#    secret_alias_value: repository/conf/user-mgt.xml//UserManager/Realm/Configuration/AdminUser/Password,false
#    password: "%{hiera('wso2::super_admin::password')}"
#
#  wso2_carbon_db_password:
#    secret_alias: Datasources.WSO2_CARBON_DB.Configuration.Password
#    secret_alias_value: repository/conf/datasources/master-datasources.xml//datasources-configuration/datasources/datasource[name='WSO2_CARBON_DB']/definition[@type='RDBMS']/configuration/password,false
#    password: "%{hiera('wso2::datasources::common::password')}"
#
#  analytics_ds_password:
#    secret_alias: Datasources.WSO2_ANALYTICS_DS.Configuration.Password
#    secret_alias_value: repository/conf/datasources/master-datasources.xml//datasources-configuration/datasources/datasource[name='WSO2_ANALYTICS_DS']/definition[@type='RDBMS']/configuration/password,false
#    password: "%{hiera('wso2::datasources::mysql::password')}"
#
#  analytics_store_ds_password:
#    secret_alias: Datasources.WSO2_ANALYTICS_STORE_DS.Configuration.Password
#    secret_alias_value: repository/conf/datasources/analytics-datasources.xml//datasources-configuration/datasources/datasource[name='WSO2_ANALYTICS_STORE_DS']/definition[@type='RDBMS']/configuration/password,false
#    password: "%{hiera('wso2::datasources::mysql::password')}"
#
#  metrics_ds_password:
#    secret_alias: Datasources.WSO2_METRICS_DS.Configuration.Password
#    secret_alias_value: repository/conf/datasources/metrics-datasources.xml//datasources-configuration/datasources/datasource[name='WSO2_METRICS_DS']/definition[@type='RDBMS']/configuration/password,false
#    password: "%{hiera('wso2::datasources::common::password')}"
#